---
title: "function_work"
author: "Li Shandross"
date: "2/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library("thief")
library("MAPA")
library("hts")
library("fable")

library(forecast)

library(lubridate)
library(tidyverse)
library(zoltr)
library(covidHubUtils)
library(stringr) 
#library(rlist)

source("forecast_fns.R")
```


```{r, message=FALSE, fig.width=12, fig.height=8}
start_date <- as.Date("2020-07-27") # a monday
end_date <- as.Date("2021-01-10")

hosp_truth_asof <- load_truth("HealthData", 
                         "inc hosp", 
                         as_of = end_date,
                         temporal_resolution="daily",
                         data_location = "covidData")


fips_code <- "04"

hosp_truth <- hosp_truth_asof %>%
  select(target_end_date, location, value) %>%
  dplyr::filter(target_end_date >= start_date,
                location == fips_code) %>%
  arrange(target_end_date)

most_recent_date <- hosp_truth_asof %>%
  slice_max(target_end_date, n=1, with_ties=FALSE) %>%
  pull(target_end_date)
end_date <- most_recent_date

ht_day <- hosp_truth$value

# create list of aggregation levels
agg_list <- list(56, 28, 14, 7, 1)

# Construct aggregates
time_period <- as.numeric(end_date - start_date) + 1
periods <- floor(time_period / 56)
remainder <- time_period - (periods * 56)
ht_day_ts_ <- ts(pull(hosp_truth, "value"), start = c(1,1), end = c(periods+1, remainder), frequency = 56) 

day_agg_ <- tsaggregates(ht_day_ts_, m = 56, aggregatelist = agg_list)
agg.names <- c("daily", "weekly", "2-weekly", "4-weekly", "8-weekly")
for(i in seq_along(day_agg_)) names(day_agg_)[[i]] <- agg.names[i]
```

``` {r extended truth data}
full_hosp_truth <- load_truth("HealthData", 
                         "inc hosp", 
                         temporal_resolution="weekly",
                         data_location = "remote_hub_repo")
                         
# an extra 1*(top agg level) of truth data to plot against forecasts
# using most up-to-date truth data
extended_truth <- full_hosp_truth %>%
  select(target_end_date, location, value) %>%
  dplyr::filter(target_end_date >= end_date,
                target_end_date <= end_date + weeks(4),
                location == "US") %>%
  arrange(target_end_date)

long_truth <- rbind(hosp_truth, extended_truth) 
# this logic is now a little strange, should the truth line be entirely the most up-to-date truth data?
# Or the truth data that was used, plus the later truth data for the forecasted period?
# If so, maybe mark them as different with line type or color

long_ts <- ts(long_truth$value, start = c(1,1), end = c(8, 29), frequency = 56) 

long_aggs <- tsaggregates(long_ts, m = 56, aggregatelist = agg_list)
for(i in seq_along(long_aggs))
   names(long_aggs)[[i]] <- agg.names[i]


for(i in seq_along(day_agg_)) names(day_agg_)[[i]] <- agg.names[i]

periods <- as.double(diff.Date(c(start_date, end_date)))/56

dates_actual_agg <- rep(start_date - weeks(1), floor(periods))
for (i in 1:length(dates_actual_agg)) {
  dates_actual_agg[i] <- start_date + (i-1)*weeks(8)
}
plot(day_agg_, main="Covid-19 Inc Hosp", xaxt = "n")
axis(1, at=1:5, labels = dates_actual_agg, line = 1.1)
```


```{r base forecasts}
pi_levels <- c(10 * (1:9), 95, 98)

# Compute base forecasts
base_fc_day <- list()
for(i in seq_along(day_agg_)){
  base_fc_day[[i]] <- forecast(auto.arima(day_agg_[[i]]), 
                               h=2*frequency(day_agg_[[i]]), 
                               level = pi_levels)
}
```


```{r sanity check sim}
nsim <- 10000
h <- frequency(day_agg_[[1]]) # 56
sim <- matrix(NA_real_, nrow = nsim, ncol = h)
arima_fit <- auto.arima(day_agg_[[1]])
# simulate.Arima(arima_fit, nsim = h)

for (i in 1:nsim) {
    try(sim[i, ] <- simulate.Arima(arima_fit, nsim = h), silent = TRUE)
}

apply(sim, 2, median) 
# sanity check: converges to mean generated by forecast() as nsim goes to infinity

# apply(sim, 2, quantile, probs=c(0.25, 0.5, 0.75))
```


``` {r reconciled forecasts}
# Reconcile forecasts - no need to write a new function for this
reconciled_fc_day <- reconcilethief(base_fc_day, aggregatelist = agg_list)

rec_test <- list()
for (i in 1:length(reconciled_fc_day)) {
  reconciled_fc_day[[i]][["mean"]][reconciled_fc_day[[i]][["mean"]] < 0] <- 0
  reconciled_fc_day[[i]][["lower"]][reconciled_fc_day[[i]][["lower"]] < 0] <- 0
  reconciled_fc_day[[i]][["upper"]][reconciled_fc_day[[i]][["upper"]] < 0] <- 0
  reconciled_fc_day[[i]][["x"]][reconciled_fc_day[[i]][["x"]] < 0] <- 0
  reconciled_fc_day[[i]][["fitted"]][reconciled_fc_day[[i]][["fitted"]] < 0] <- 0
  rec_test[[i]] <- modify_at(reconciled_fc_day[[i]], .at = c("mean", "lower", "upper", "x", "fitted"), ~.^4)
  rec_test[[i]] <- modify_at(rec_test[[i]], .at = "residuals", 
             function(fit) fit = rec_test[[i]][["x"]]-rec_test[[i]][["fitted"]])
}

#et <- extended_test

# Plot forecasts before and after reconciliation
# This code is not optimized for plotting when there are many levels
par(mfrow=c(3,2), mai=c(0.35,0.5,0.35,0.35))
for(i in seq_along(base_fc_day)) { 
  plot(reconciled_fc_day[[i]], main=agg.names[i], 
       shadecols = c("light gray", "#C2DDEE", "#00458F") , 
       xaxt = "n", #axes = FALSE,
       ylim = c(0, max(reconciled_fc_day[[i]]$x, reconciled_fc_day[[i]]$upper))) 
  lines(reconciled_fc_day[[i]]$mean, col=4, lwd=2) # plots blue reconciled forecasts line
  lines(base_fc_day[[i]]$mean, col='red') # plots red mean line
  if(!is.null(et)) lines(et[[i]], col='black', lwd=1.5, lty = "dotted")
  #  axis(1, at=1:6, labels = dates_actual_forecast)
  axis(2)
}
points(base_fc_day[[length(base_fc_day)]]$mean, col= 'red')
```

Turn Reconciled Forecasts List into Tibble of Forecasts
```{r}
# Lower Forecasts
low_fc <- as_tibble(reconciled_fc_day[[1]][["lower"]]) # Change TS object to tibble
low_fc[low_fc < 0] <- 0 # Ensure all negative values are changed to 0
  
old_col_names <- colnames(low_fc)
new_col_names <- rep("string", length(old_col_names))
for (i in 1:length(old_col_names)) {
  new_col_names[i] <- as.character(((100-pi_levels[i])/2)/100)
  # new_col_names[i] <- ifelse(str_length(new_col_names[i]) <= 4, 
  #                            paste(new_col_names[i], "0", sep=""), new_col_names[i])
}

colnames(low_fc) <- c(new_col_names)

# Higher Forecasts
high_fc <- as_tibble(reconciled_fc_day[[1]][[6]]) # Change TS object to tibble
high_fc[high_fc < 0] <- 0 # Ensure all negative values are changed to 0
  
old_col_names <- colnames(high_fc)
new_col_names <- rep("string", length(old_col_names))
for (i in 1:length(old_col_names)) {
  new_col_names[i] <- as.character((100-((100-pi_levels[i])/2))/100)
  # new_col_names[i] <- ifelse(str_length(new_col_names[i]) <= 4, 
  #                            paste(new_col_names[i], "0", sep=""), new_col_names[i])
}

colnames(high_fc) <- c(new_col_names)

# Point Forecasts
point_fc <- as_tibble(reconciled_fc_day[[1]][[4]]) %>% # Change TS object to tibble
  transmute(`0.5`= as.numeric(x))
point_fc[point_fc < 0] <- 0 # Ensure all negative values are changed to 0

model_name = "base_arima"
# Join forecasts together
reconciled_forecasts <- cbind(low_fc, point_fc, high_fc) %>%
  mutate(forecast_date = end_date, 
         horizon = as.numeric(rownames(low_fc)),
         temporal_resolution = "day",
         target_end_date = forecast_date + days(horizon)) %>%
  pivot_longer(1:23, "quantile", "value") %>%
  arrange(target_end_date, quantile) %>%
  mutate(model = model_name,
         location = fips_code, 
         type = "quantile",
         target_variable = "inc hosp",
         quantile = as.numeric(quantile)) %>%
  select(model, location, forecast_date, horizon, temporal_resolution, 
         target_variable, target_end_date, type, quantile, value) %>%
  left_join(filter(hub_locations, fips == fips_code), by = c("location" = "fips"))

```

```{r}
locations <- filter(hub_locations, geo_type == "state", population >= 500000)
fips_vec <- c("02", "01")
# might want to perform another similar map_dfr over the dates

t2 <- map_dfr(
  .x = fips_vec,
  .f = function(fips_code) {
    thief_wrapper(full_hosp_truth, ts_col = "value", 
  start_date, end_date, fips_code,
  aggregate_levels = list(28, 14, 7, 1), frequency = 28,
  pi_levels = pi_levels, model_name = "model",
  plot.aggregates = FALSE, plot.forecasts = FALSE)
  }
)
```


## Functions

```{r aggregate_thief and plot_agg, message=FALSE, fig.width=12, fig.height=8}
full_hosp_truth <- load_truth("HealthData", 
                         "inc hosp", 
                         temporal_resolution="weekly",
                         data_location = "remote_hub_repo")


start_date <- as.Date("2020-07-27") # a monday
end_date <- as.Date("2021-07-26")

fips_code <- "US"

aggregate_thief_df <- # aggregate levels list should be in order of smallest to largest level
  function(ts_col = "value", start_date, end_date, fips_code, aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56, df = NULL) {
    # if df is not a a data frame, stop "Please provide a a data frame"
    if (is.null(df)) {
    df <- load_truth("HealthData", 
                         "inc hosp", 
                         as_of = end_date,
                         temporal_resolution="daily",
                         data_location = "covidData")
    } else {
      df <- df
      warning("forecasts will be based on static truth data")
    }
    ts_col <- ts_col
    # if aggregate_levels == NULL, stop "you have not provided any aggregate levels"
    fips_code <- fips_code
    # if fips_code! %in% state_fips_codes, stop "Please provide the fips code of a US location"
    # if (start_date == NULL) # first target_end_date, else
    start_date <- as.Date(start_date)
    # likewise for end_date, else
    end_date <- as.Date(end_date)
    
    agg_list <- aggregate_levels
    freq <- frequency
    
    hosp_truth <- df %>%
      select(target_end_date, location, value) %>%
      dplyr::filter(target_end_date >= start_date,
                    target_end_date <= end_date,
                    location == fips_code)

      # Construct time series      
      time_period <- as.numeric(end_date - start_date) + 1
      periods <- floor(time_period / freq)
      remainder <- time_period - (periods * freq)
      ht_day_ts_ <- ts(pull(hosp_truth, ts_col), 
                       start = c(1, 1), end = c(periods+1, remainder), 
                       frequency = freq)
      
      # Construct temporal hierarchy
      day_agg_ <- tsaggregates(ht_day_ts_, m = freq, aggregatelist = agg_list)
      agg.names <- c("daily", "weekly", "2-weekly", "4-weekly", "8-weekly")
      for(i in seq_along(day_agg_)) {
        names(day_agg_)[[i]] <- agg.names[i]
      }
      
      day_agg_
  }


plot_thief_agg <- function(temporal_hierarchy, start_date) {
  start_date <- as.Date(start_date)

  # Make actual date labels for plot
  freq <-frequency(temporal_hierarchy[[1]])
  periods <- floor(length(temporal_hierarchy[[1]]) / freq)
  dates_actual_agg <- rep(start_date - weeks(1), periods + 1)
  for (i in 1:length(dates_actual_agg)) {
    dates_actual_agg[i] <- start_date + (i-1)*weeks(freq/7)
  }

  # Plot temporal hierarchy data
  plot(temporal_hierarchy, main="Covid-19 Inc Hosp", xaxt = "n")
  axis(1, at=1:(periods + 1), labels = dates_actual_agg, line = 1.1)
}
```   


```{r compute_base_forecasts}
pi_levels <- c(10 * (1:9), 95, 98)
# Compute base forecasts
compute_base_forecasts <-
  function(temporal_hierarchy, pi_levels = c(10 * (1:9), 95, 98)) {
    # if temporal_hierarchy == NULL
    temporal_hierarchy <- temporal_hierarchy
    pi_levels <- pi_levels
    base_forecasts <- list()
    for(i in seq_along(temporal_hierarchy)){
      base_forecasts[[i]] <- 
        forecast(auto.arima(temporal_hierarchy[[i]]), 
                 h=frequency(temporal_hierarchy[[i]])*2,
                 level = pi_levels)
    }
    #return(base_forecasts)
    base_forecasts
  }
```

```{r reconcile forecasts and adjust for forth root transformation}
transform_forecasts <- function(forecasts) {
  if (is.null(forecasts)) {stop('Please provide a forecast object to transform.')}
  
  fc_trans <- list()
  for (i in 1:length(forecasts)) {
    forecasts[[i]][["mean"]][forecasts[[i]][["mean"]] < 0] <- 0
    forecasts[[i]][["lower"]][forecasts[[i]][["lower"]] < 0] <- 0
    forecasts[[i]][["upper"]][forecasts[[i]][["upper"]] < 0] <- 0
    forecasts[[i]][["x"]][forecasts[[i]][["x"]] < 0] <- 0
    forecasts[[i]][["fitted"]][forecasts[[i]][["fitted"]] < 0] <- 0
    forecasts[[i]][["mean"]] <- forecasts[[i]][["mean"]]^4
    forecasts[[i]][["lower"]] <- forecasts[[i]][["lower"]]^4
#    fc_trans[[i]] <- modify_at(forecasts[[i]], .at = c("mean", "lower", "upper", "x", "fitted"), ~.^4)
#    fc_trans[[i]] <- modify_at(fc_trans[[i]], .at = "residuals", 
#               function(fit) fit = fc_trans[[i]][["x"]]-fc_trans[[i]][["fitted"]])
  }
  return(forecasts)
}

transform_forecasts(forecasts=reconciled_fc_day)
rec_test
```
  
``` {r plot_thief and extra data functions}
# FIX ME: logic issue re what iteration of truth data to use
extended_truth_data <-
  function(df, ts_col = "value", start_date, end_date, fips_code, aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56) {
    # an extra 1*(top agg level) of truth data to plot against forecasts
    aggregate_thief_df(df, ts_col, start_date, end_date + days(frequency), fips_code, aggregate_levels, frequency) 
  }

get_ts_dates <-
  function(start_date, end_date, frequency = 56) {
    # vector of actual dates
    freq <- frequency
    time_period <- as.numeric(end_date - start_date) + 1
    periods <- floor(time_period / freq)
    dates_actual_forecast <- rep(start_date - weeks(1), periods + 3)
    for (i in 1:length(dates_actual_forecast)) {
      dates_actual_forecast[i] <- start_date + (i-1)*weeks(freq/7)
    }
    return(dates_actual_forecast)
  }
  
plot_thief <- 
  function(base_forecasts, reconciled_forecasts, ts_dates, extended_truth = NULL) {
    par(mfrow=c(ceiling(length(base_forecasts)/2), 2), mai=c(0.35,0.5,0.35,0.35))
    for(i in seq_along(base_forecasts))
    { # This code is not optimized for plotting when there are many levels
      plot(reconciled_forecasts[[i]], main=agg.names[i], shadecols = c("light gray", "#C2DDEE", "#00458F") , 
          xaxt = "n", #axes = FALSE,
          ylim = c(0, max(reconciled_forecasts[[i]]$x, reconciled_forecasts[[i]]$upper))) 
      lines(reconciled_forecasts[[i]]$mean, col=4, lwd=2) # plots blue reconciled forecasts line
      lines(base_forecasts[[i]]$mean, col='red') # plots red mean line
      if(!is.null(extended_truth)) lines(extended_truth[[i]], col='black', lwd=1.5, lty = "dotted") # plots extended truth data against forecasts
      axis(1, at=1:(periods + 4), labels = ts_dates) # changes axis labels to provided dates
      axis(2)
    }
    points(base_forecasts[[length(base_forecasts)]]$mean, col= 'red')
  }

```

```{r transform_to_hub_df}
# This function uses the most this aggregate level of forecasts

transform_to_hub_df <- function(forecast_list, model_name = "model", end_date, fips_code) {
  # If forecast_list == NULL, stop "you have not provided any forecasts"
  # if forecast_list is not a a data frames, stop "Please provide a a data frames"
  # if fips_code == NULL, stop "you have not provided a"
  # if fips_code! %in% state_fips_codes, stop "Please provide the fips code of a US location"
    
  thief_forecast <- forecast_list
  model_name <- model_name
  fips_code <- fips_code

  # Lower Forecasts
  low_fc <- as_tibble(thief_forecast[[1]][["lower"]]) # Change TS object to tibble
  low_fc[low_fc < 0] <- 0 # Ensure all negative values are changed to 0
    
  old_col_names <- colnames(low_fc)
  new_col_names <- rep("string", length(old_col_names))
  for (i in 1:length(old_col_names)) {
    new_col_names[i] <- as.character(((100-pi_levels[i])/2)/100)
  }
  colnames(low_fc) <- c(new_col_names)
  
  # Higher Forecasts
  high_fc <- as_tibble(thief_forecast[[1]][["upper"]]) # Change TS object to tibble
  high_fc[high_fc < 0] <- 0 # Ensure all negative values are changed to 0
    
  old_col_names <- colnames(high_fc)
  new_col_names <- rep("string", length(old_col_names))
  for (i in 1:length(old_col_names)) {
    new_col_names[i] <- as.character((100-((100-pi_levels[i])/2))/100)
  }
  colnames(high_fc) <- c(new_col_names)
  
  
  # Point Forecasts
  point_fc <- as_tibble(thief_forecast[[1]][["mean"]]) %>% # Change TS object to tibble
    transmute(`0.5`= as.numeric(x))
  point_fc[point_fc < 0] <- 0 # Ensure all negative values are changed to 0


  # Join forecasts together
  hub_df <- cbind(low_fc, point_fc, high_fc) %>%
    mutate(forecast_date = end_date, 
           horizon = as.numeric(rownames(low_fc)),
           temporal_resolution = "day",
           target_end_date = forecast_date + days(horizon)) %>%
    pivot_longer(1:(2*length(pi_levels) + 1), "quantile", "value") %>%
    arrange(target_end_date, quantile) %>%
    mutate(model = model_name,
           location = fips_code, 
           type = "quantile",
           target_variable = "inc hosp",
           quantile = as.numeric(quantile)) %>%
    select(model, location, forecast_date, horizon, temporal_resolution, 
           target_variable, target_end_date, type, quantile, value) %>%
    left_join(filter(hub_locations, fips == fips_code), by = c("location" = "fips"))
  
    hub_df

}
```


```{r func testing and thief_wrapper}
test <- aggregate_thief_df(NULL, ts_col = "value", start_date, end_date, fips_code, aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56) 
plot_thief_agg(test, start_date)
temp <- compute_base_forecasts(test, pi_levels)
temp_reconciled <- reconcilethief(temp, aggregatelist = agg_list) # produces a warning

extended_test <- extended_truth_data(full_hosp_truth, ts_col = "value", start_date, end_date, fips_code, aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56)
dates_test <- get_ts_dates(start_date, end_date, frequency = 56) 
plot_thief(base_forecasts= temp, reconciled_forecasts= temp_reconciled, ts_dates = dates_test, extended_truth = extended_test)
temp_rec_df <- transform_to_hub_df(temp_reconciled, end_date, "US", pi_levels)

thief_wrapper <- 
  function(ts_col = "value", start_date, end_date, fips_code, aggregate_levels, frequency, pi_levels, model_name, df=NULL, plot.aggregates = TRUE, plot.forecasts = TRUE) {
    ts_col <- ts_col
    # if (start_date == NULL) # first target_end_date, else
    if(!is.Date(start_date)) start_date <- as.Date(start_date)
    # likewise for end_date, else
    if(!is.Date(end_date)) end_date <- as.Date(end_date)
    # if df is not a a data frame, stop "Please provide a a data frame"
    # if fips_code == NULL, stop "you have not provided a fips code", else
    fips_code <- fips_code
    # if fips_code! %in% state_fips_codes, stop "Please provide the fips code of a US location"
    # if aggregate_levels == NULL, stop "you have not provided any aggregate levels"
    # if pi_levels == NULL, warning "you have not provided any PI levels, using default levels"
    
    if (is.null(df)) {
      df <- load_truth("HealthData", 
                         "inc hosp", 
                         as_of = end_date,
                         temporal_resolution="daily",
                         data_location = "covidData")
    } else {
      df <- df
      warning("forecasts will be based on static truth data")
    }

    thief_aggregation <- suppressWarnings(aggregate_thief_df(ts_col, start_date, end_date, fips_code, aggregate_levels, frequency, df))
    
    if (plot.aggregates == TRUE) {plot_thief_agg(thief_aggregation, start_date) }
    base_fc <- compute_base_forecasts(thief_aggregation, pi_levels)
    reconciled_fc <- reconcilethief(base_fc, aggregatelist = aggregate_levels)

    if (plot.forecasts == TRUE) {
      extended_agg <- extended_truth_data(df, ts_col, start_date, end_date, fips_code, aggregate_levels, frequency)
      ts_dates <- get_ts_dates(start_date, end_date, frequency = frequency)
      plot_thief(base_fc, reconciled_fc, ts_dates, extended_agg)
    }
    
    hub_df <- transform_to_hub_df(reconciled_fc, model_name, end_date, fips_code)
    model_info <- tibble(model = model_name, forecast_date = end_date, location = fips_code, base_fc_obj = base_fc, rec_fc_obj = reconciled_fc)
    
    return(list(hub_df, model_info)) 
  }

model_info <- tibble(model = "mod", forecast_date = end_date, location = fips_code, base_fc_obj = base_fc_day, rec_fc_obj = reconciled_fc_day, level = agg_list)
  
hub_test <- thief_wrapper(NULL, ts_col = "value",
  start_date = start_date, end_date = end_date, fips_code = "US",
  aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56,
  pi_levels = pi_levels,
  plot.aggregates = FALSE, plot.forecasts = FALSE)
```

```{r map}
locations <- filter(hub_locations, geo_type == "state", population >= 500000) %>%
  pull(fips)
fips_vec <- c("US", "01")
# might want to perform another similar map_dfr over the dates

# function
covid_thief <- 
  function(df = NULL, ts_col, start_date, end_date, fips_vec, aggregate_levels, frequency, pi_levels, model_name) {
    if (is.null(df)) {
      df <- load_truth("HealthData", 
                         "inc hosp", 
                         as_of = end_date,
                         temporal_resolution="daily",
                         data_location = "covidData")
    } else {
      df <- df
      warning("forecasts will be based on static truth data")
    }
    
    all_locs_list <- map(
      .x = fips_vec,
      .f = function(fips_code) {
        suppressWarnings(thief_wrapper(ts_col, start_date, end_date, fips_code, aggregate_levels, frequency, pi_levels, model_name, df=NULL,plot.aggregates = FALSE, plot.forecasts = FALSE))
      }
    )
    n <- length(fips_vec)
    all_locs_fc <- map_dfr(.x = 1:n, .f = function(i) {all_locs_list[[i]][[1]]})
    all_locs_mod <- map_dfr(.x = 1:n, .f = function(i) {all_locs_list[[i]][[2]]})
    
    return(list(all_locs_fc, all_locs_mod))
  }
  
t4 <- covid_thief(NULL, ts_col = "value", 
  start_date, end_date, fips_vec,
  aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56,
  pi_levels = c(10 * (1:9), 95, 98), "model")

full_locs_forecasts <- covid_thief(full_hosp_truth, ts_col = "value", 
  start_date, end_date, fips_vec = locations,
  aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56,
  pi_levels = pi_levels, "model")

# Not needed for parallelizing
covid_thief_period <-
  function(df, ts_col, start_date, end_date, fc_period, fips_vec, aggregate_levels, frequency, pi_levels, model_name) {
    all_locs_df <- map_dfr(
      .x = fc_period,
      .f = function(fc_vec) {
        start_vec = c(start_date + days(fc_vec))
        end_vec = c(end_date + days(fc_vec))
        
        thief_wrapper(df, ts_col, start_vec, end_vec, fips_code, aggregate_levels, frequency, pi_levels, model_name, plot.aggregates = FALSE, plot.forecasts = FALSE) 
      }
    )
    return(all_locs_df)
  }

full_dates_forecasts <- covid_thief_period(full_hosp_truth, ts_col = "value", 
  start_date, end_date, fc_period = c(0: 6), fips_vec = fips_vecs,
  aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56,
  pi_levels = pi_levels, "model")

start_vec <- c(start_date + days(0:6))
end_vec <- c(end_date + days(1:6))

lapply(full_hosp_truth, aggregate_thief_df, ts_col = "value", 
  start_date = start_vec, end_date = end_date, fips_code = "US", 
  aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56)
  
test <- aggregate_thief_df(full_hosp_truth, ts_col = "value", start_date, end_date, fips_code, aggregate_levels = list(56, 28, 14, 7, 1), frequency = 56) 
```
