---
title: "plot_all_locations"
author: "Li Shandross"
date: "`r Sys.Date()`"
geometry: "left=1.25cm,right=0.75cm,top=1.5cm,bottom=1.5cm"
output: 
  pdf_document: 
    fig_width: 36
    fig_height: 27
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library("thief")
library(forecast)
library(lubridate)
library(tidyverse)
library(zoltr)
library(covidHubUtils)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
full_hosp_truth <- load_truth("HealthData", 
                         "inc hosp", 
                         as_of=as.Date("2022-10-01"),
                         temporal_resolution="weekly",
                         data_location = "covidData")

inc_hosp_targets <- paste(0:35, "day ahead inc hosp")
analysis <- "testing"

if (analysis == "original") {
  load("../data/loadedfc_scores_df.RData")
} else if (analysis == "versioned") {
  load("../data/versioned_fc_df.RData")
} else if (analysis == "extended") {
  load("../data/baseline_fc_scores_extended.RData")
  load("../data/extended_fcv_thief_old_small.RData")
  load("../data/extended_fcv_thief_new_small.RData")
  load("../data/extended_fcv_thief_ensemble_small.RData")
  load("../data/extended_fcv_sarima_small.RData")

  date_limits <- c(as.Date("2020-10-01"), as.Date("2021-11-01"))
  fc_dates <- c(as.Date("2020-12-07") + weeks(4*(0:11)), pull(distinct(fcv_sarima_small, forecast_date)))
  locs <- distinct(fcv_sarima_small, location) %>% pull()

fc_ver <- fcv_thief_ensemble_small %>%
  rbind(fcv_sarima_small, fcv_thief_new_small, fcv_thief_old_small) %>% 
  rbind(filter(fc_baseline, forecast_date %in% fc_dates)) %>%
  mutate(model = ifelse(model == "COVIDhub-baseline", "zCOVIDhub-baseline", model))
  
} else if (analysis == "testing") {
  load("../data/baseline_fc_scores_testing.RData")
  load("../data/testing_fcv_thief_old_small.RData")
  load("../data/testing_fcv_thief_new_small.RData")
#  load("../data/testing_fcv_thief_ensemble_small.RData")

  date_limits <- c(as.Date("2021-09-01"), as.Date("2022-10-01"))
  fc_dates <- c(as.Date("2021-11-01") + weeks(4*(0:11)), pull(distinct(fc_testing_thief_old_small, forecast_date)))
  locs <- distinct(fc_testing_thief_old_small, location) %>% pull()
  
  fc_ver <- #fcv_thief_ensemble_small %>%
    rbind(fc_testing_thief_new_small, fc_testing_thief_old_small) %>% 
    rbind(filter(forecasts_testing_baseline, forecast_date %in% fc_dates)) %>%
    mutate(model = ifelse(model == "COVIDhub-baseline", "zCOVIDhub-baseline", model))
}

#locs <- locs 
#locs <- "US"
models <- fc_ver %>% distinct(model) %>% pull(1)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
for (i in 1:length(locs)) {
  fdat <- fc_ver %>% 
    filter(location == locs[i], 
           horizon %in% c(1:28))
  
  if (locs[i] %in% c("US", "22")) {
  fdat <- fdat %>%
    filter(forecast_date > as.Date("2021-01-04"))
  }
  
  p <- plot_forecasts(fdat, 
                      target_variable = "inc hosp", 
                      intervals = c(.50, .95),
                      truth_source = "HealthData",
                      use_median_as_point = TRUE,
                      facet = model ~.,
                      facet_nrow = 6,
                      fill_by_model = TRUE, 
                      plot=FALSE)

  pt <- p +
    scale_x_date(name=NULL, limits=date_limits, date_breaks = "3 months", date_labels = "%b %y") +
    coord_cartesian(ylim = c(0, max(filter(full_hosp_truth, location==locs[i], target_end_date <= date_limits[2])$value * 1.15))) +
    theme(axis.ticks.length.x = unit(0.5, "cm"),
          axis.text.x = element_text(vjust = 7, hjust = -0.2),
          legend.position = "none")
          
  print(pt)
}
```
