---
title: "Score Forecasts"
author: "Li Shandross"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    fig_height: 21
    fig_caption: yes
    fig_width: 14
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library("thief")
library(forecast)
library(lubridate)
library(tidyverse)
library(zoltr)
library(covidHubUtils)
library(patchwork)
library(surveillance)
library(tidytext)
library(stringr)

# parallelize code
library(doParallel)
num_cores <- detectCores(logical=TRUE)
cl <- makeCluster(num_cores-1)
registerDoParallel(cl)
```

## Load in truth data and forecasts

```{r, message=FALSE, warning=FALSE, results=FALSE}
analysis <- "extended" # original, versioned, extended
ifelse(analysis != "extended", train_end_date <- as.Date("2021-07-05"), train_end_date <- as.Date("2021-10-31"))
            
inc_hosp_targets <- paste(0:30, "day ahead inc hosp")
fips <- filter(hub_locations, geo_type == "state", population >= 500000) %>% pull(fips)
ifelse(analysis == "extended", 
       mon_fc_dates <- c(as.Date("2020-12-07") + weeks(0:46)),
       mon_fc_dates <- c(as.Date("2020-12-07") + weeks(0:29)))

if (analysis == "original") {
  models <-c("Base_arima_4root", "Base_arima_noTransform", "Multiple3_arima_4root", "Multiple3_arima_noTransform", "Topmost8_arima_4root", "Topmost8_arima_noTransform")
  load("../data/loadedfc_scores_df.RData") # original unversioned forecasts and scores
  load("../data/baseline_fc_scores.RData") # original baseline forecasts and scores
  fc_plot <- rbind(forecasts_df, forecasts_baseline)
  scores_df <-scores_df %>%
    mutate(horizon_wk=ceiling(as.numeric(target_end_date-forecast_date)/7))
} else if (analysis == "versioned") {
  models <- sort(paste("THieF_", c(4, 8, 12), "wk-", c(rep("4root", 3), rep("noTransform", 3)), sep=""))
  load("../data/versioned_fc_df.RData") # versioned forecasts and scores
  load("../data/baseline_fc_scores.RData") # original baseline forecasts and scores
  actual_fc_dates <- distinct(forecasts_ver, forecast_date) %>% pull(1)
  mon_dates_df <- tibble(forecast_date = actual_fc_dates, mon_fc_dates)
  fc_plot <- rbind(forecasts_ver, forecasts_baseline)

  scores <- scores_ver %>%
    left_join(mon_dates_df, by = "forecast_date") %>%
    mutate(horizon_wk=ceiling(as.numeric(target_end_date-mon_fc_dates)/7)) %>%
    select(-mon_fc_dates) %>%
    filter(horizon_wk %in% 1:4)
} else if (analysis == "extended") {
  all_thief <- sort(paste("THieF_", c(1:4, 6, 8, 12), "wk-", c(rep("4root", 7), rep("noTransform", 7)), sep=""))[c(3:14, 1:2)]
  thief_new <- sort(paste("THieF_", c(1:3, 6), "wk-", c(rep("4root", 4), rep("noTransform", 4)), sep=""))
  thief_old <- sort(paste("THieF_", c(4, 8, 12), "wk-", c(rep("4root", 3), rep("noTransform", 3)), sep=""))
  sarima_models <- sort(paste("sarima_s", c(1, 7), c(rep("-4root", 2), rep("-noTransform", 2)), sep=""))
  thief_ensembles <- paste("THieF_ensemble-", c("mean", paste(rep("train", 6), c(1, 3, 6.5, 10, 15, 20, 25), sep="")), sep="")
  models <- c(all_thief, sarima_models, thief_ensembles)

  # load("../data/extended_fcv_thief_old.RData")
  # load("../data/extended_fcv_thief_new.RData")
  # load("../data/extended_fcv_thief_ensemble.RData")
  # load("../data/extended_fcv_sarima.RData")
  load("../data/extended_fcv_thief_old_small.RData")
  load("../data/extended_fcv_thief_new_small.RData")
  load("../data/extended_fcv_thief_ensemble_small.RData")
  load("../data/extended_fcv_sarima_small.RData")
  load("../data/extended_scv_thief_old.RData")
  load("../data/extended_scv_thief_new.RData")
  load("../data/extended_scv_thief_ensemble.RData")
  load("../data/extended_scv_sarima.RData")
  load("../data/baseline_fc_scores_extended.RData")

  actual_fc_dates <- distinct(scores_version_sarima, forecast_date) %>% pull(1)
  mon_dates_df <- tibble(forecast_date = actual_fc_dates, mon_fc_dates)
  fc_plot <- fcv_thief_ensemble_small %>%
    rbind(fcv_sarima_small, fcv_thief_new_small, fcv_thief_old_small) %>% 
    rbind(forecasts_baseline) 
  scores <- scores_version_thief_ensemble %>%
    rbind(scores_version_sarima, scores_version_thief_old, scores_version_thief_new) %>%
    left_join(mon_dates_df, by = "forecast_date") %>%
    mutate(horizon_wk=ceiling(as.numeric(target_end_date-mon_fc_dates)/7)) %>%
    select(-mon_fc_dates) %>%
    filter(horizon_wk %in% 1:4)
}
            
load("../data/versioned_truth_training.RData")
full_hosp_truth <- load_truth("HealthData", 
                         "inc hosp", 
                         as_of=as.Date("2022-04-06"),
                         temporal_resolution="weekly",
                         data_location = "covidData")

scores_baseline <- score_baseline %>%
  mutate(horizon=as.numeric(horizon),
    horizon_wk=ceiling(as.numeric(target_end_date-forecast_date)/7)) %>%
  filter(horizon_wk %in% 1:4)
```


## Plot Forecasts

```{r, warning=FALSE, message=FALSE}
locs <- full_hosp_truth %>%
  filter(target_end_date <= train_end_date) %>%
  group_by(location) %>%
  summarize(cum_value=sum(value)) %>%
  ungroup() %>%
  arrange(desc(cum_value)) %>%
  filter(row_number() %in% c(1, 2, 53)) %>%
  pull(location)

ifelse(analysis == "extended", 
       fc_dates <- c(as.Date("2020-12-07") + weeks(4*(0:11)), actual_fc_dates[1+4*(0:11)]),
       fc_dates <- c(as.Date("2020-12-07") + weeks(4*(0:7)), actual_fc_dates[1+4*(0:7)]))

for (i in 1:3) {
  fdat <- fc_plot %>%
    filter(location == locs[i], forecast_date %in% fc_dates, horizon <= 28)
  
  if (locs[i] == "US" | locs[i] == "22") {
  fdat <- fdat %>%
    filter(forecast_date > as.Date("2021-01-04"))
  }
  
  p <- plot_forecasts(fdat, 
#                      models = c(),
#                      truth_data = filter(full_hosp_truth, target_end_date <= as.Date("2021-05-03")),
                      target_variable = "inc hosp", 
                      intervals = c(.5, .95), 
                      truth_source = "HealthData",
                      use_median_as_point = TRUE,
                      facet = model ~.,
                      facet_nrow = ifelse(analysis == "extended", 7, 4),
#                      facet_scales = "free_y",
                      fill_by_model = TRUE, 
                      plot=FALSE)

  pt <- p +
    scale_x_date(name=NULL, limits=c(as.Date("2020-10-01"), train_end_date), 
              date_breaks = "4 months", date_labels = "%b %y") +
    coord_cartesian(ylim = c(0, max(filter(full_hosp_truth, location==locs[i])$value) * 1.15)) +
    theme(axis.ticks.length.x = unit(0.5, "cm"),
          axis.text.x = element_text(vjust = 7, hjust = -0.2),
          legend.position = "none")
          
  print(pt)
}
```


## Score forecasts

### Overall metrics
```{r, warning=FALSE, message=FALSE}
# US National
overall_metrics_US <- scores %>%
  rbind(scores_baseline) %>%
  filter(#target_end_date <= train_end_date,
         forecast_date >= as.Date("2021-01-11"),
         location == "US") %>%
  group_by(model) %>%
  summarize(
    wis = mean(wis), 
    mae = mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
overall_metrics_US <- overall_metrics_US %>%
  mutate(
    rwis = wis/pull(filter(overall_metrics_US, model == "COVIDhub-baseline"), 2),
    rmae = mae/pull(filter(overall_metrics_US, model == "COVIDhub-baseline"), 3),
    #cov_50 = cov_50/abs(pull(filter(overall_metrics_US, model == "COVIDhub-baseline"), 4)-0.5),
    #rcov_95 = cov_95/abs(pull(filter(overall_metrics_US, model == "COVIDhub-baseline"), 5)-0.95),
  ) %>% 
  mutate(across(cov_50:rmae, round, digits=3)) %>%
  arrange(wis)
knitr::kable(overall_metrics_US)

# States
overall_metrics_states <- scores %>%
  rbind(scores_baseline) %>%
  filter(ifelse(location == "22", forecast_date > as.Date("2021-01-04"), location != "US")) %>%
  group_by(model) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
overall_metrics_states <- overall_metrics_states %>%
  mutate(
    rwis = wis/pull(filter(overall_metrics_states, model == "COVIDhub-baseline"), 2),
    rmae = mae/pull(filter(overall_metrics_states, model == "COVIDhub-baseline"), 3),
    #cov_50 = cov_50/abs(pull(filter(overall_metrics_states, model == "COVIDhub-baseline"), 4)-0.5),
    #rcov_95 = cov_95/abs(pull(filter(overall_metrics_states, model == "COVIDhub-baseline"), 5)-0.95),
  ) %>% 
  mutate(across(where(is.numeric), round, digits=3)) %>%
  arrange(wis)
knitr::kable(overall_metrics_states)
```


### Overall metrics (last 17 weeks)
```{r, warning=FALSE, message=FALSE}
# US National
last_metrics_US <- scores %>%
  rbind(scores_baseline) %>%
  filter(target_end_date <= train_end_date,
         forecast_date > train_end_date - weeks(ifelse(analysis == "extended", 17, 12)),
         forecast_date >= as.Date("2021-01-11"),
         location == "US") %>%
  group_by(model) %>%
  summarize(
    wis = round(mean(wis), digits=1), 
    mae = round(mean(abs_error), digits=1),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
last_metrics_US <- last_metrics_US %>%
  mutate(
    rwis = wis/pull(filter(last_metrics_US, model == "COVIDhub-baseline"), 2),
    rmae = mae/pull(filter(last_metrics_US, model == "COVIDhub-baseline"), 3),
    #cov_50 = cov_50/abs(pull(filter(last_metrics_US, model == "COVIDhub-baseline"), 4)-0.5),
    #rcov_95 = cov_95/abs(pull(filter(last_metrics_US, model == "COVIDhub-baseline"), 5)-0.95),
  ) %>% 
  mutate(across(cov_50:rmae, round, digits=3)) %>%
  arrange(wis)
knitr::kable(last_metrics_US)

# States
last_metrics_states <- scores %>%
  rbind(scores_baseline) %>%
  filter(ifelse(location == "22", forecast_date > as.Date("2021-01-04"), location != "US"),
          forecast_date <= train_end_date,
         forecast_date > train_end_date - weeks(ifelse(analysis == "extended", 17, 12))) %>%
  group_by(model) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
last_metrics_states <- last_metrics_states %>%
  mutate(
    rwis = wis/pull(filter(last_metrics_states, model == "COVIDhub-baseline"), 2),
    rmae = mae/pull(filter(last_metrics_states, model == "COVIDhub-baseline"), 3),
    #cov_50 = cov_50/abs(pull(filter(last_metrics_states, model == "COVIDhub-baseline"), 4)-0.5),
    #rcov_95 = cov_95/abs(pull(filter(last_metrics_states, model == "COVIDhub-baseline"), 5)-0.95),
  ) %>% 
  mutate(across(where(is.numeric), round, digits=3)) %>%
  arrange(wis)
knitr::kable(last_metrics_states)
```

### Horizon week metrics
```{r, warning=FALSE, message=FALSE}
# US National
horizon_wk_metrics_US <- scores %>%
  rbind(scores_baseline) %>%
  filter(#target_end_date <= train_end_date,
         forecast_date >= as.Date("2021-01-11"),
         location == "US") %>%
  group_by(model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
horizon_wk_metrics_US <- horizon_wk_metrics_US %>%
  mutate(
    rwis = case_when(
      horizon_wk == 1 ~ wis / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 1), 3), 
      horizon_wk == 2 ~ wis / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 2), 3), 
      horizon_wk == 3 ~ wis / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 3), 3), 
      horizon_wk == 4 ~ wis / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 4), 3), 
    ),
    rmae = case_when(
      horizon_wk == 1 ~ mae / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 1), 4), 
      horizon_wk == 2 ~ mae / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 2), 4), 
      horizon_wk == 3 ~ mae / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 3), 4), 
      horizon_wk == 4 ~ mae / pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 4), 4), 
    ),
    # rcov_50 = case_when(
    #   horizon_wk == 1 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 1), 5)-0.5),
    #   horizon_wk == 2 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 2), 5)-0.5),
    #   horizon_wk == 3 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 3), 5)-0.5),
    #   horizon_wk == 4 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 4), 5)-0.5),
    # ),
    # rcov_95 = case_when(
    #   horizon_wk == 1 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 1), 6)-0.95),
    #   horizon_wk == 2 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 2), 6)-0.95),
    #   horizon_wk == 3 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 3), 6)-0.95),
    #   horizon_wk == 4 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_US, model == "COVIDhub-baseline", horizon_wk == 4), 6)-0.95),
  ) %>% 
  mutate(across(where(is.numeric), round, digits=3), across(wis:mae, round, digits=1)) %>%
  arrange(horizon_wk, wis)
knitr::kable(horizon_wk_metrics_US)

# Aggregated for all states and territories
horizon_wk_metrics_states <- scores %>%
  rbind(scores_baseline) %>%
  filter(ifelse(location == "22", forecast_date > as.Date("2021-01-04"), location != "US")) %>%
  group_by(model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
horizon_wk_metrics_states <- horizon_wk_metrics_states %>%
  mutate(
    rwis = case_when(
      horizon_wk == 1 ~ wis / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 1), 3), 
      horizon_wk == 2 ~ wis / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 2), 3), 
      horizon_wk == 3 ~ wis / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 3), 3), 
      horizon_wk == 4 ~ wis / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 4), 3), 
    ),
    rmae = case_when(
      horizon_wk == 1 ~ mae / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 1), 4), 
      horizon_wk == 2 ~ mae / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 2), 4), 
      horizon_wk == 3 ~ mae / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 3), 4), 
      horizon_wk == 4 ~ mae / pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 4), 4), 
    ),
    # rcov_50 = case_when(
    #   horizon_wk == 1 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 1), 5)-0.5),
    #   horizon_wk == 2 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 2), 5)-0.5),
    #   horizon_wk == 3 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 3), 5)-0.5),
    #   horizon_wk == 4 ~ (cov_50-0.5) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 4), 5)-0.5),
    # ),
    # rcov_95 = case_when(
    #   horizon_wk == 1 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 1), 6)-0.95),
    #   horizon_wk == 2 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 2), 6)-0.95),
    #   horizon_wk == 3 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 3), 6)-0.95),
    #   horizon_wk == 4 ~ (cov_95-0.95) / abs(pull(filter(horizon_wk_metrics_states, model == "COVIDhub-baseline", horizon_wk == 4), 6)-0.95),
  ) %>% 
  mutate(across(where(is.numeric), round, digits=3)) %>%
  arrange(horizon_wk, wis)
knitr::kable(horizon_wk_metrics_states)
```

```{r, message=FALSE, warning=FALSE}  
if (analysis == "original") {
  model_names <- c("COVIDhub-baseline", models[3:6], models[1:2])
  model_colors <- c("black", "red", "orange", "green", "blue", "purple", "magenta")
} else if (analysis == "versioned") {
  model_names <- c("COVIDhub-baseline", models[3:6], models[1:2])
  model_colors <- c("black", "red", "orange", "green", "blue", "purple", "magenta")
} else if (analysis == "extended") {
  model_names <- c("COVIDhub-baseline", models)
  model_colors <- c("black", rep(c("red", "orange", "yellow", "green",
               "blue", "purple", "magenta", "#b9865f", "#644e3d"), each=2), 
               "#dfdfdf", "#cacaca", "#a8a8a8", "#878787", "#6d6d6d", "#5f5f5f", "#4a4a4a", "#3d3d3d")
}
wis_hzn_plot_US <- horizon_wk_metrics_US %>%
mutate(
  specification = gsub(".*_(.+)-.*", "\\1", model),
  transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                        str_detect(model, "ensemble") ~ "noTransform",
                        !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
  type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
) %>%
ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
  geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
  geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  coord_cartesian(ylim = c(min(horizon_wk_metrics_US$wis)*0.9, median(filter(horizon_wk_metrics_US, horizon_wk==4)$wis)*1.5)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
  labs(title="US", x="Horizon Week", y="Average WIS")
              
wis_hzn_plot_states <- horizon_wk_metrics_states %>%
mutate(
  specification = gsub(".*_(.+)-.*", "\\1", model),
  transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                        str_detect(model, "ensemble") ~ "noTransform",
                        !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
  type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
) %>%
ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
  geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
  geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  coord_cartesian(ylim = c(min(horizon_wk_metrics_states$wis)*0.9, median(filter(horizon_wk_metrics_states, horizon_wk==4)$wis)*1.25)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
  labs(title="States", x="Horizon Week", y="Average WIS")
       
wis_hzn_plot_US + wis_hzn_plot_states +
  plot_layout(ncol = 2, guides='collect') &
  theme(legend.position='bottom')
```

### Metrics by wave
```{r, warning=FALSE, message=FALSE}
# US National
wave_metrics_US <- scores %>%
  rbind(scores_baseline) %>%
  filter(target_end_date <= train_end_date,
         forecast_date >= as.Date("2021-01-11"),
         location == "US") %>%
  mutate(
    wave = case_when(
      forecast_date <= as.Date("2021-03-17") ~"winter21",
      forecast_date %in% c(as.Date("2021-03-17"):as.Date("2021-07-05")) ~ "alpha",
      forecast_date >= as.Date("2021-07-05") ~"delta"
    )
  ) %>%
  group_by(wave, model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
wave_baseline_US <- filter(wave_metrics_US, model == "COVIDhub-baseline")
wave_metrics_US <- wave_metrics_US %>%
  mutate(
    rwis = case_when(
      horizon_wk == 1 & wave == "alpha" ~ wis / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 1), 4),
      horizon_wk == 2 & wave == "alpha" ~ wis / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 2), 4),
      horizon_wk == 3 & wave == "alpha" ~ wis / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 3), 4),
      horizon_wk == 4 & wave == "alpha" ~ wis / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 4), 4),
      horizon_wk == 1 & wave == "winter21" ~ wis / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 1), 4),
      horizon_wk == 2 & wave == "winter21" ~ wis / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 2), 4),
      horizon_wk == 3 & wave == "winter21" ~ wis / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 3), 4),
      horizon_wk == 4 & wave == "winter21" ~ wis / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 4), 4),
      horizon_wk == 1 & wave == "delta" ~ wis / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 1), 4),
      horizon_wk == 2 & wave == "delta" ~ wis / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 2), 4),
      horizon_wk == 3 & wave == "delta" ~ wis / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 3), 4),
      horizon_wk == 4 & wave == "delta" ~ wis / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 4), 4),
    ),
    rmae = case_when(
      horizon_wk == 1 & wave == "alpha" ~ mae / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 1), 5),
      horizon_wk == 2 & wave == "alpha" ~ mae / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 2), 5),
      horizon_wk == 3 & wave == "alpha" ~ mae / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 3), 5),
      horizon_wk == 4 & wave == "alpha" ~ mae / pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 4), 5),
      horizon_wk == 1 & wave == "winter21" ~ mae / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 1), 5),
      horizon_wk == 2 & wave == "winter21" ~ mae / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 2), 5),
      horizon_wk == 3 & wave == "winter21" ~ mae / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 3), 5),
      horizon_wk == 4 & wave == "winter21" ~ mae / pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 4), 5),
      horizon_wk == 1 & wave == "delta" ~ mae / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 1), 5),
      horizon_wk == 2 & wave == "delta" ~ mae / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 2), 5),
      horizon_wk == 3 & wave == "delta" ~ mae / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 3), 5),
      horizon_wk == 4 & wave == "delta" ~ mae / pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 4), 5),
    ),
    # rcov_50 = case_when(
    #   horizon_wk == 1 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 1), 6)-0.5),
    #   horizon_wk == 2 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 2), 6)-0.5),
    #   horizon_wk == 3 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 3), 6)-0.5),
    #   horizon_wk == 4 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 4), 6)-0.5),
    #   horizon_wk == 1 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 1), 6)-0.5),
    #   horizon_wk == 2 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 2), 6)-0.5),
    #   horizon_wk == 3 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 3), 6)-0.5),
    #   horizon_wk == 4 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 4), 6)-0.5),
    #   horizon_wk == 1 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 1), 6)-0.5),
    #   horizon_wk == 2 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 2), 6)-0.5),
    #   horizon_wk == 3 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 3), 6)-0.5),
    #   horizon_wk == 4 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 4), 6)-0.5),
    # ),
    # rcov_95 = case_when(
    #   horizon_wk == 1 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 1), 7)-0.95),
    #   horizon_wk == 2 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 2), 7)-0.95),
    #   horizon_wk == 3 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 3), 7)-0.95),
    #   horizon_wk == 4 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "alpha", horizon_wk == 4), 7)-0.95),
    #   horizon_wk == 1 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 1), 7)-0.95),
    #   horizon_wk == 2 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 2), 7)-0.95),
    #   horizon_wk == 3 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 3), 7)-0.95),
    #   horizon_wk == 4 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "winter21", horizon_wk == 4), 7)-0.95),
    #   horizon_wk == 1 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 1), 7)-0.95),
    #   horizon_wk == 2 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 2), 7)-0.95),
    #   horizon_wk == 3 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 3), 7)-0.95),
    #   horizon_wk == 4 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_US, wave == "delta", horizon_wk == 4), 7)-0.95),
    # )
  ) %>% 
  mutate(across(where(is.numeric), round, digits=3), across(wis:mae, round, digits=1)) %>%
  arrange(wave, horizon_wk, wis)
  
knitr::kable(wave_metrics_US)

# Aggregated for all states and territories
wave_metrics_states <- scores %>%
  rbind(scores_baseline) %>%
  filter(ifelse(location == "22", forecast_date > as.Date("2021-01-04"), location != "US")) %>%
  mutate(
    wave = case_when(
      forecast_date <= as.Date("2021-03-17") ~"winter21",
      forecast_date %in% c(as.Date("2021-03-17"):as.Date("2021-07-05")) ~"alpha",
      forecast_date >= as.Date("2021-07-05") ~"delta"
    )
  ) %>%
  group_by(wave, model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  ) 
wave_baseline_states <- filter(wave_metrics_states, model == "COVIDhub-baseline")
wave_metrics_states <- wave_metrics_states %>%
  mutate(
    rwis = case_when(
      horizon_wk == 1 & wave == "alpha" ~ wis / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 1), 4),
      horizon_wk == 2 & wave == "alpha" ~ wis / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 2), 4),
      horizon_wk == 3 & wave == "alpha" ~ wis / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 3), 4),
      horizon_wk == 4 & wave == "alpha" ~ wis / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 4), 4),
      horizon_wk == 1 & wave == "winter21" ~ wis / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 1), 4),
      horizon_wk == 2 & wave == "winter21" ~ wis / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 2), 4),
      horizon_wk == 3 & wave == "winter21" ~ wis / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 3), 4),
      horizon_wk == 4 & wave == "winter21" ~ wis / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 4), 4),
      horizon_wk == 1 & wave == "delta" ~ wis / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 1), 4),
      horizon_wk == 2 & wave == "delta" ~ wis / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 2), 4),
      horizon_wk == 3 & wave == "delta" ~ wis / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 3), 4),
      horizon_wk == 4 & wave == "delta" ~ wis / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 4), 4),
    ),
    rmae = case_when(
      horizon_wk == 1 & wave == "alpha" ~ mae / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 1), 5),
      horizon_wk == 2 & wave == "alpha" ~ mae / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 2), 5),
      horizon_wk == 3 & wave == "alpha" ~ mae / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 3), 5),
      horizon_wk == 4 & wave == "alpha" ~ mae / pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 4), 5),
      horizon_wk == 1 & wave == "winter21" ~ mae / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 1), 5),
      horizon_wk == 2 & wave == "winter21" ~ mae / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 2), 5),
      horizon_wk == 3 & wave == "winter21" ~ mae / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 3), 5),
      horizon_wk == 4 & wave == "winter21" ~ mae / pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 4), 5),
      horizon_wk == 1 & wave == "delta" ~ mae / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 1), 5),
      horizon_wk == 2 & wave == "delta" ~ mae / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 2), 5),
      horizon_wk == 3 & wave == "delta" ~ mae / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 3), 5),
      horizon_wk == 4 & wave == "delta" ~ mae / pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 4), 5),
    ),
    # rcov_50 = case_when(
    #   horizon_wk == 1 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 1), 6)-0.5),
    #   horizon_wk == 2 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 2), 6)-0.5),
    #   horizon_wk == 3 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 3), 6)-0.5),
    #   horizon_wk == 4 & wave == "alpha" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 4), 6)-0.5),
    #   horizon_wk == 1 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 1), 6)-0.5),
    #   horizon_wk == 2 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 2), 6)-0.5),
    #   horizon_wk == 3 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 3), 6)-0.5),
    #   horizon_wk == 4 & wave == "winter21" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 4), 6)-0.5),
    #   horizon_wk == 1 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 1), 6)-0.5),
    #   horizon_wk == 2 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 2), 6)-0.5),
    #   horizon_wk == 3 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 3), 6)-0.5),
    #   horizon_wk == 4 & wave == "delta" ~ (cov_50-0.5) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 4), 6)-0.5),
    # ),
    # rcov_95 = case_when(
    #   horizon_wk == 1 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 1), 7)-0.95),
    #   horizon_wk == 2 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 2), 7)-0.95),
    #   horizon_wk == 3 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 3), 7)-0.95),
    #   horizon_wk == 4 & wave == "alpha" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "alpha", horizon_wk == 4), 7)-0.95),
    #   horizon_wk == 1 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 1), 7)-0.95),
    #   horizon_wk == 2 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 2), 7)-0.95),
    #   horizon_wk == 3 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 3), 7)-0.95),
    #   horizon_wk == 4 & wave == "winter21" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "winter21", horizon_wk == 4), 7)-0.95),
    #   horizon_wk == 1 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 1), 7)-0.95),
    #   horizon_wk == 2 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 2), 7)-0.95),
    #   horizon_wk == 3 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 3), 7)-0.95),
    #   horizon_wk == 4 & wave == "delta" ~ (cov_95-0.95) / abs(pull(filter(wave_baseline_states, wave == "delta", horizon_wk == 4), 7)-0.95),
    # )
  ) %>% 
  mutate(across(where(is.numeric), round, digits=3)) %>%
  arrange(wave, horizon_wk, wis)
  
knitr::kable(wave_metrics_states)
```

```{r, message=FALSE, warning=FALSE}
wis_hzn_plot_winter21_US <- wave_metrics_US %>%
  filter(wave == "winter21") %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
  ) %>%
  ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
  labs(title="Winter '21 Wave (US)", x="Horizon Week", y="Average WIS")
   
wis_hzn_plot_alpha_US <- wave_metrics_US %>%
  filter(wave == "alpha") %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
  ) %>%
  ungroup() %>%
ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
  geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
  geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  coord_cartesian(
    ylim = c(min(filter(wave_metrics_US, wave == "alpha")$wis)*0.9, 
            median(filter(wave_metrics_US, horizon_wk==4, wave == "alpha")$wis)*1.5)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
  labs(title="Alpha Wave (US)", x="Horizon Week", y="Average WIS")

if (analysis == "extended") {  
  wis_hzn_plot_delta_US <- wave_metrics_US %>%
    filter(wave == "delta") %>%
    mutate(
      specification = gsub(".*_(.+)-.*", "\\1", model),
      transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                            str_detect(model, "ensemble") ~ "noTransform",
                            !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
      type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
    ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
    coord_cartesian(
      ylim = c(min(filter(wave_metrics_US, wave == "delta")$wis)*0.9, 
              median(filter(wave_metrics_US, horizon_wk==4, wave == "delta")$wis)*1.5)) +
    scale_color_manual(breaks = model_names, values = model_colors) +
    scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
    labs(title="Delta Wave (US)", x="Horizon Week", y="Average WIS")
}  

wis_hzn_plot_winter21_states <- wave_metrics_states %>%
  filter(wave == "winter21") %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                        !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
  ) %>%
  ungroup() %>%
ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
  geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
  geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
  labs(title="Winter '21 Wave (States)", x="Horizon Week", y="Average WIS")
   
wis_hzn_plot_alpha_states <- wave_metrics_states %>%
  filter(wave == "alpha") %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                        !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
  ) %>%
ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
  geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
  geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  coord_cartesian(
    ylim = c(min(filter(wave_metrics_states, wave == "alpha")$wis)*0.8, 
            median(filter(wave_metrics_states, horizon_wk==4, wave == "alpha")$wis)*1.6)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
  labs(title="Alpha Wave (states)", x="Horizon Week", y="Average WIS")

if (analysis == "extended") {      
  wis_hzn_plot_delta_states <- wave_metrics_states %>%
    filter(wave == "delta") %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
  ) %>%
  ggplot(mapping=aes(x=horizon_wk, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
    coord_cartesian(
      ylim = c(min(filter(wave_metrics_states, wave == "delta")$wis)*0.9, 
              median(filter(wave_metrics_states, horizon_wk==4, wave == "delta")$wis)*1.5)) +
    scale_color_manual(breaks = model_names, values = model_colors) +
    scale_linetype_manual(breaks=c("noTransform", "4root"), values=c("solid", "dashed")) +
    labs(title="Delta Wave (states)", x="Horizon Week", y="Average WIS")
}  

if (analysis == "extended") { 
  wis_hzn_plot_winter21_US + wis_hzn_plot_winter21_states + 
    wis_hzn_plot_alpha_US + wis_hzn_plot_alpha_states +
    wis_hzn_plot_delta_US + wis_hzn_plot_delta_states +
    plot_layout(ncol = 2, guides='collect') &
    theme(legend.position='bottom') 
} else {
  wis_hzn_plot_winter21_US + wis_hzn_plot_winter21_states + 
    wis_hzn_plot_alpha_US + wis_hzn_plot_alpha_states +
    plot_layout(ncol = 2, guides='collect') &
    theme(legend.position='bottom') 
}
```


### By forecast date (week)

```{r, warning=FALSE, message=FALSE}
# Also the WIS graphs aren't readable for the models with smaller WIS
# change to rWIS? log transform?

# US National
forecast_date_metrics_US <- scores %>%
  left_join(mon_dates_df, by = "forecast_date") %>%
  filter(#target_end_date <= train_end_date,
         forecast_date > as.Date("2021-01-04"),
         location == "US") %>%
  select(model, horizon, horizon_wk, forecast_date = mon_fc_dates, target_end_date, 
        true_value, abs_error, wis, coverage_50, coverage_95) %>%
  group_by(forecast_date, model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  )

baseline_fc_date_metrics_US <- scores_baseline %>%
  filter(target_end_date <= train_end_date,
         forecast_date > as.Date("2021-01-11"),
         location == "US") %>%
  select(model, horizon, horizon_wk, forecast_date, target_end_date, 
        true_value, abs_error, wis, coverage_50, coverage_95) %>%
  group_by(forecast_date, model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  )

# WIS
wis_1wk_plot_US <- forecast_date_metrics_US %>%
  rbind(baseline_fc_date_metrics_US) %>%
  filter(horizon_wk == 1) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "WIS (1-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')

wis_4wk_plot_US <- forecast_date_metrics_US %>%
  rbind(baseline_fc_date_metrics_US) %>%
  filter(horizon_wk == 4) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  coord_cartesian(ylim = c(0, max(filter(forecast_date_metrics_US, horizon_wk==4, forecast_date < as.Date("2021-02-01"))$wis)*1.25)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "WIS (4-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')


# 95% PI Coverage
cov95_1wk_plot_US <- forecast_date_metrics_US %>%
  rbind(baseline_fc_date_metrics_US) %>%
  filter(horizon_wk == 1) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=cov_95, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  geom_hline(aes(yintercept=0.95)) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "95% PI Coverage (1-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')  

cov95_4wk_plot_US <- forecast_date_metrics_US %>%
  rbind(baseline_fc_date_metrics_US) %>%
  filter(horizon_wk == 4) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=cov_95, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "95% PI Coverage (4-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')

wis_1wk_plot_US + wis_4wk_plot_US + 
  cov95_1wk_plot_US + cov95_4wk_plot_US +
  plot_layout(ncol = 2, guides='collect') &
  theme(legend.position='bottom')
```

```{r}  
# States
forecast_date_metrics_states <- scores %>%
  left_join(mon_dates_df, by = "forecast_date") %>%
  filter(ifelse(location == "22", forecast_date > as.Date("2021-01-04"), location != "US")) %>%
  select(model, horizon, horizon_wk, forecast_date = mon_fc_dates, target_end_date, 
          true_value, abs_error, wis, coverage_50, coverage_95) %>%
  group_by(forecast_date, model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  )

baseline_fc_date_metrics_states <- scores_baseline %>%
  select(model, horizon, horizon_wk, forecast_date, target_end_date, 
        true_value, abs_error, wis, coverage_50, coverage_95) %>%
  group_by(forecast_date, model, horizon_wk) %>%
  summarize(
    wis = mean(wis), mae=mean(abs_error),
    cov_50 = mean(coverage_50),
    cov_95 = mean(coverage_95)
  )

# WIS
wis_1wk_plot_states <- forecast_date_metrics_states %>%
  rbind(baseline_fc_date_metrics_states) %>%
  filter(horizon_wk == 1) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  coord_cartesian(ylim = c(0, max(filter(forecast_date_metrics_states, horizon_wk==1, forecast_date < as.Date("2020-12-10"))$wis)*1.25)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "WIS (1-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')

wis_4wk_plot_states <- forecast_date_metrics_states %>%
  rbind(baseline_fc_date_metrics_states) %>%
  filter(horizon_wk == 4) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=wis, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  coord_cartesian(ylim = c(0, max(filter(forecast_date_metrics_states, horizon_wk==4, forecast_date < as.Date("2021-02-10"))$wis)*1.15)) +
  coord_cartesian(ylim = c(0, 175)) +
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "WIS (4-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')


# 95% PI Coverage
cov95_1wk_plot_states <- forecast_date_metrics_states %>%
  rbind(baseline_fc_date_metrics_states) %>%
  filter(horizon_wk == 1) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=cov_95, group=model)) +
    geom_point(mapping=aes(col=model, shape=type), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  geom_hline(aes(yintercept=0.95)) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "95% PI Coverage (1-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')  

cov95_4wk_plot_states <- forecast_date_metrics_states %>%
  rbind(baseline_fc_date_metrics_states) %>%
  filter(horizon_wk == 4) %>%
  mutate(
    specification = gsub(".*_(.+)-.*", "\\1", model),
    transform = case_when(model == "COVIDhub-baseline" ~ "noTransform", 
                          str_detect(model, "ensemble") ~ "noTransform",
                          !(str_detect(model, "ensemble") && str_detect(model, "baseline")) ~ sub(".*-", "", model)),
    type = ifelse(str_detect(model, "ensemble"), "ensemble", sub("_.*", "", model))
    ) %>%
  ggplot(mapping=aes(x=forecast_date, y=cov_95, group=model)) +
    geom_point(mapping=aes(col=model), alpha = 0.8) +
    geom_line(mapping=aes(col=model, linetype=transform), alpha = 0.8) +
  geom_hline(aes(yintercept=0.95)) +
  scale_x_date(name=NULL, date_breaks = "1 month", date_labels = "%b") + 
  scale_color_manual(breaks = model_names, values = model_colors) +
  labs(title = "95% PI Coverage (4-week)") +
  theme(axis.ticks.length.x = unit(0.1, "cm"),
        axis.text.x = element_text(vjust = 2, hjust = -0.2),
        legend.position = 'bottom')

wis_1wk_plot_states + wis_4wk_plot_states + 
  cov95_1wk_plot_states + cov95_4wk_plot_states +
  plot_layout(ncol = 2, guides='collect') &
  theme(legend.position='bottom')
```

### Metrics By Location
```{r, message=FALSE, warning=FALSE}
#reorder states, reorder models 
theme_set(theme_bw())
data("hub_locations")

model_levels <- pull(overall_metrics_states, model)

inc_scores <- rbind(scores, scores_baseline) %>%
  filter(target_end_date <= train_end_date,
         ifelse(location == "22" | location == "US", 
                forecast_date > as.Date("2021-01-04"), 
                forecast_date >= as.Date("2020-12-05")))

###################################################################################################
# Calculate pairwise WIS

# helper function
next_monday <- function(date){
  nm <- rep(NA, length(date))
  for(i in seq_along(date)){
    nm[i] <- date[i] + (0:6)[weekdays(date[i] + (0:6)) == "Monday"]
  }
  return(as.Date(nm, origin = "1970-01-01"))
}


# bring all forecast_dates to Monday:
inc_scores$forecast_date <- next_monday(inc_scores$forecast_date)

# select relevant columns:
heat_scores <- inc_scores %>% 
  left_join(hub_locations[1:2], by = c("location" = "fips")) %>%
  select("model", "forecast_date", "location", "location_name", "horizon", "abs_error", "wis", "horizon_wk") %>% 
  droplevels()

# the included models and locations:
models <- unique(heat_scores$model)
locations <- unique(heat_scores$location)
location_names <- unique(heat_scores$location_name)

# function for pairwise comparison of models
pairwise_comparison <- function(heat_scores, mx, my, subset = rep(TRUE, nrow(heat_scores)),
                                permutation_test = FALSE){
  
  ############## This line had been deleted, but needs to be included ##########################
  # apply subset:
  heat_scores <- heat_scores[subset, ]
  
  # subsets of available heat_scores for both models:
  subx <- subset(heat_scores, model == mx)
  suby <- subset(heat_scores, model == my)
  
  # merge together and restrict to overlap:
  sub <- merge(subx, suby, by = c("forecast_date", "location", "horizon"),
               all.x = FALSE, all.y = FALSE)
  
  # compute ratio:
  ratio <- sum(sub$wis.x) / sum(sub$wis.y)
  
  # perform permutation tests:
  if(permutation_test){
    pval <- permutationTest(sub$wis.x, sub$wis.y,
                            nPermutation = 999)$pVal.permut
    
    # aggregate by forecast date:
    sub_fcd <- aggregate(cbind(wis.x, wis.y) ~ forecast_date, data = sub, FUN = mean) 
    pval_fcd <- permutationTest(sub_fcd$wis.x, sub_fcd$wis.y,
                                nPermutation = 999)$pVal.permut
  }else{
    pval <- NULL
    pval_fcd <- NULL
  }
  
  return(list(ratio = ratio, pval = pval, pval_fcd = pval_fcd, mx = mx, my = my))
}

# compute pairwise and relative WIS for each location separately:
for(i in seq_along(locations)){
  
  # select location:
  loc <- locations[i]
  loc_name <- location_names[i]
  
  # matrix to store:
  results_ratio_temp <- matrix(ncol = length(models),
                               nrow = length(models),
                               dimnames = list(models, models)) 
  
  # run pairwise comparison for chosen location:
  for(mx in seq_along(models)){
    for(my in 1:mx){
      pwc <- pairwise_comparison(heat_scores = filter(heat_scores, horizon_wk %in% 1:4), mx = models[mx], my = models[my],
                                 permutation_test = FALSE, # disable permutation test to speed up things
                                 subset = filter(heat_scores, horizon_wk %in% 1:4)$location == loc) # this will subset to the respective location inside the function
      results_ratio_temp[mx, my] <- pwc$ratio
      results_ratio_temp[my, mx] <- 1/pwc$ratio
    }
  }
  
  # compute the geometric means etc
  ind_baseline <- which(rownames(results_ratio_temp) == "COVIDhub-baseline")
  geom_mean_ratios_temp <- exp(rowMeans(log(results_ratio_temp[, -ind_baseline]), na.rm = TRUE))
  ratios_baseline_temp <- results_ratio_temp[, "COVIDhub-baseline"]
  ratios_baseline2_temp <- geom_mean_ratios_temp/geom_mean_ratios_temp["COVIDhub-baseline"]
  
  # summarize results:
  to_add <- data.frame(model = names(ratios_baseline2_temp),
                       location = loc,
                       location_name = loc_name,
                       relative_wis = ratios_baseline2_temp,
                       log_relative_wis = log(ratios_baseline2_temp))
  
  # append to already stored:
  if(i == 1){ # initialize at first location
    average_by_loc <- to_add
  }else{
    average_by_loc <- rbind(average_by_loc, to_add)
  }
}


## plot of true data by state, tiled
truth_dat <- full_hosp_truth %>%
  filter(target_end_date <= train_end_date) %>%
  group_by(location, location_name) %>%
  summarize(cum_value=sum(value)) %>%
  ungroup() %>%
  mutate(location_name = reorder(location_name, cum_value)) %>%
  pull(location_name)


average_by_loc_to_plot <- average_by_loc %>%
  mutate(location_name = fct_relevel(location_name, levels(truth_dat)),
         relative_wis_text = sprintf("%.2f", round(relative_wis, 2)),
         log_relative_wis = log2(relative_wis),
         model = fct_relevel(model, model_levels)) %>%
  filter(!is.na(relative_wis)) 


# plot:
fig_wis_loc <- ggplot(average_by_loc_to_plot, 
                      aes(x=model, y=location_name, 
                          fill= scales::oob_squish(log_relative_wis, range = c(-2, 1.5)))) +
  geom_tile() +
  geom_text(aes(label = relative_wis_text), size = 2.5) + # I adapted the rounding
  scale_fill_gradient2(low = "steelblue", high = "red", midpoint = 0, na.value = "grey50", 
                       name = "Relative WIS", 
                       breaks = c(-2,-1,0,1), 
                       labels =c("0.25", 0.5, 1, "2+")) + 
  xlab(NULL) + ylab(NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 9),
        #                            color=ifelse(
        #                              levels(average_by_loc_to_plot$model) %in% models_to_highlight,
        #                              "red", "black")),
        axis.title.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),
        title = element_text(size = 9))

print(fig_wis_loc)
```


